### ISSUE TITLE
How to get file "train_strokes.p"

### ISSUE THREAD

**Issue by wangqiang9** [tcl9876/Diffusion-Handwriting-Generation#3]
https://github.com/tcl9876/Diffusion-Handwriting-Generation/blob/26a2dc33648b26b49eb1d11af118e0dc71fa8698/train.py#L88
In this line, what is the file "train_strokes.p" and how to get it?
thanks a lot.

**Comment by tcl9876** [comment]
@XDUWQ 

The file "train_strokes.p" is a pickle file that stores the dataset (the training examples in the form of a list). 

To get the file, first download the following things from https://fki.tic.heia-fr.ch/databases/download-the-iam-on-line-handwriting-database :

data/lineStrokes-all.tar.gz 
data/lineImages-all.tar.gz 
ascii-all.tar.gz  

Then try running preprocessing.py through the command line - preprocessing.py should create and save the pickle file.

Hope this helps, and let me know if you have further issues/questions

**Comment by XDUWQ** [comment]
> @XDUWQ
> 
> The file "train_strokes.p" is a pickle file that stores the dataset (the training examples in the form of a list).
> 
> To get the file, first download the following things from https://fki.tic.heia-fr.ch/databases/download-the-iam-on-line-handwriting-database :
> 
> data/lineStrokes-all.tar.gz data/lineImages-all.tar.gz ascii-all.tar.gz
> 
> Then try running preprocessing.py through the command line - preprocessing.py should create and save the pickle file.
> 
> Hope this helps, and let me know if you have further issues/questions

**Comment by wangqiang9** [comment]
problem is solved！thanks a lot
