### ISSUE TITLE
custom handwriting?

### ISSUE THREAD

**Issue by SB2020-eye** [tcl9876/Diffusion-Handwriting-Generation#6]
Can one use this to produce a custom handwriting style? That is, if I have an image (or even many, many images) of someone's handwriting, could I use this so that it would reproduce any text I input and produce an image of that text in my chosen custom handwriting style?

**Comment by tcl9876** [comment]
Hi, 
It does support conditioning on a custom handwriting style via the "--writersource" argument.  To get good results you might have to preprocess, which I believe involves cropping the handwriting picture so it's just a single line of writing, and turning it to grayscale. I don't think it supports using multiple style images though.

hope this helps.
